### ISSUE TITLE
Wo Updates

### ISSUE THREAD

**Issue by itsDkiller** [Kaktushose/pascord#2]
# Lass den Meme-Wrapper bitte nicht aussterben, min jung

**Comment by Kaktushose** [comment]
erstmal Tinder, kannst aber gerne contributen, wenn dir das projekt so sehr am herzen liegt

**Comment by itsDkiller** [comment]
@Kaktushose Ich kann dir gern bei den Docs helfen, aber damit ich Pascal lerne muss viel passieren 🤣

**Comment by Kaktushose** [comment]
solche Leute brauchen wir hier nicht!
